### ISSUE TITLE
Problem with /dev/ttyACM0

### ISSUE THREAD

**Issue by borongyuan** [xanmod/linux#79]
Hi,
I've install linux-xanmod-rt on LattePanda Alpha 864s (https://www.lattepanda.com/products/lattepanda-alpha-864s.html), which has an Arduino Leonardo as co-processor. However I am not able to upload code to Arduino after installed the xanmod kernel. I'm already in the dialout group. After switching back to original kernel (linux-image-5.4.0-42-generic), the code uploading is fine. With the orginal kernel, the Arduino's serial port is /dev/ttyACM0. But with xanmod kernel, there exists /dev/ttyACM0 and /dev/ttyACM1. I've tried both ports and they are not working. I've also tried linux-xanmod-lts and linux-xanmod-rt-edge, the same problem. I use lsmod to check modules and cdc_acm is loaded. Any suggestions?
Thanks

**Comment by xanmod** [comment]
Fixed in current versions?

**Comment by borongyuan** [comment]
After upgraded to 5.4.59-rt36-xanmod1, the problem still exists.

**Comment by xanmod** [comment]
Send your /var/log/kern.log, `lsusb -v > lsusb.log` and `sudo lshw > lshw.log`

**Comment by borongyuan** [comment]
I have exported logs from xanmod-rt kernel and default generic kernel.
[Google Drive](https://drive.google.com/drive/folders/1SMWdBkp3bYq9xqu9rdAM1cQAKpisx0H0?usp=sharing)
Thanks
